podTemplate(cloud: 'kubernetes', containers: [
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'bitnami/git', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'git', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '',
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent'), 
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'node:18.20-alpine', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'node', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '',
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent'), 
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'harbor.thepostway.com/google/kaniko-project/executor:v1.23.2-debug', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'kaniko', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '', 
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent'),
    containerTemplate(
        args: '9999999', 
        command: 'sleep', 
        image: 'fluxcd/helm-operator:1.4.4', 
        livenessProbe: containerLivenessProbe(execArgs: '', failureThreshold: 0, initialDelaySeconds: 0, periodSeconds: 0, successThreshold: 0, timeoutSeconds: 0), 
        name: 'helm', 
        resourceLimitCpu: '', 
        resourceLimitEphemeralStorage: '', 
        resourceLimitMemory: '', 
        resourceRequestCpu: '', 
        resourceRequestEphemeralStorage: '', 
        resourceRequestMemory: '', 
        workingDir: '/home/jenkins/agent')
    ], 
    inheritFrom: ' ', 
    namespace: 'cicd', 
    volumes: [
        secretVolume(defaultMode: '', mountPath: '/kaniko/.docker', optional: false, secretName: 'kaniko-secret')
    ]) {
    node(POD_LABEL) {

        def gitBranch = 'develop'
        def cmd = ''
        def mode = 'develop'
        def tag = 'latest'
        def gitRevision = ''
        def workspace = ''

        stage("git clone") {
            container("git") {
                script {
                    try {
                        // get workspace in jenkins agent
                        workspace = pwd()

                        // get data from webhook
                        if (env.gitlabBranch != null) {
                            gitBranch = "${env.gitlabBranch}";
                        } else {
                            gitBranch = "${gitBranch}";
                        }

                        // check mode in develop, staging or production
                        if (gitBranch.indexOf("develop") > -1 || gitBranch.indexOf("feature") > -1) {
                            mode = 'develop'
                        } else if (gitBranch.indexOf("release") > -1 || gitBranch.indexOf("hotfix") > -1) {
                            mode = 'staging'
                        } else if (gitBranch.indexOf("master") > -1 || gitBranch.indexOf("main") > -1) {
                            mode = 'production'
                        }
                    } catch (ex) {
                        gitBranch = "develop";
                        mode = 'develop';
                    }

                    // git clone code
                    git branch: "${gitBranch}", credentialsId: "${gitCred}", url: "${gitUrl}"

                    // add git safe directory
                    sh "git config --global --add safe.directory ${workspace}"

                    // get git revision
                    gitRevision = sh(script: "git log -n 1 --pretty=format:'%H'", returnStdout: true).substring(0, 16)

                    if (mode == 'production') {
                        tag = sh(script: 'git tag --points-at HEAD | tail -1', returnStdout: true)
                        tag = tag.trim()
                    }
                }
            }
        }

        stage("pre-build") {
            container("node") {
                ansiColor('xterm') {
                    script {
                        try {
                            sh "npm install --verbose --force"
                        } catch (ex) {
                            cleanWs()
                            error ex.getMessage()
                        }
                    }
                }
            }
        }

        stage("build") {
            container("node") {
                ansiColor('xterm') {
                    script {
                        sh "npm run build"
                    }
                }
            }
        }

        stage('build by kaniko') {
            container('kaniko') {
                ansiColor('xterm') {
                    script {
                        try {
                            def image = ''
                            def preImage = "harbor.thepostway.com/cardinal/spend-analytic/web"
                            def tagName = 'latest'

                            if (mode == 'develop') {
                                image = "${preImage}/dev"
                                tag = tagName
                            } else if (mode == 'staging') {
                                image = "${preImage}/stg"
                                tag = tagName
                            } else if (mode == 'production') {
                                image = "${preImage}/prod"
                                tag = tag
                            } else {
                                image = "${preImage}/dev"
                                tag = tagName
                            }

                            cmd = [
                                "--dockerfile ${workspace}/.kaniko/web/Dockerfile",
                                "--context ${workspace}",
                                "--destination=${image}:${tag}",
                                "--compressed-caching=false",
                                "--snapshot-mode=redo"
                            ].join(' ')
                            sh "/kaniko/executor ${cmd}"
                        } catch (ex) {
                            cleanWs()
                            error ex.getMessage()
                        }
                    }
                }
            }
        }

        stage('deploy') {
            ansiColor('xterm') {
                script {
                    try {
                        dir('.chart') {
                            sh "echo ${kubeCred} | base64 -d -w 0 >> config.yaml"
                        }
                    } catch (ex) {
                        cleanWs()
                        error ex.getMessage()
                    }

                    def helmNamespace = 'cardinal'
                    def helmValue = ''

                    // if else with split by mode name
                    if (mode == 'develop') {
                        helmNamespace = "${helmNamespace}-dev"
                        helmValue = "values/simpitec/values-web-dev.yaml"
                    } else if (mode == 'staging') {
                        helmNamespace = "${helmNamespace}-stg"
                        helmValue = "values/simpitec/values-web-stg.yaml"
                    } else if (mode == 'production') {
                        helmNamespace = "${helmNamespace}"
                        helmValue = "values/simpitec/values-web.yaml"
                    }

                    container('helm') {
                        try {
                            dir('.chart') {
                                // upgrade config and value
                                cmd = [
                                    "apply",
                                    "-f namespace-secret-simpitec.yaml",
                                    "--kubeconfig=config.yaml",
                                    "--context ${kubeContextName}",
                                ].join(' ')
                                sh "kubectl ${cmd}"

                                // helm upgrade kube
                                cmd = [
                                    'upgrade',
                                    '--install',
                                    "--kubeconfig=config.yaml",
                                    "--kube-context ${kubeContextName}",
                                    "--namespace ${helmNamespace}",
                                    "--set image.tag=${tag}",
                                    "-f ${helmValue}",
                                    "analytic-spend-web ."
                                ].join(' ')
                                sh "helm3 ${cmd}"

                                // delete app by selector instance
                                if (mode != 'production') {
                                    cmd = [
                                        'delete',
                                        'pod',
                                        "--kubeconfig=config.yaml",
                                        "--context ${kubeContextName}",
                                        "--namespace ${helmNamespace}",
                                        "--selector=app.kubernetes.io/instance=analytic-spend-web",
                                    ].join(' ')
                                    sh "kubectl ${cmd}"
                                }
                            }
                        } catch (ex) {
                            // cleanWs()
                            error ex.getMessage()
                        }
                    }
                }
            }
        }
    }
}
