apiVersion: v1
kind: Namespace
metadata:
  name: cardinal
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: cardinal
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIudGhlcG9zdHdheS5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoibDM4NWZxMmJrNnk5YzVhMmRub24iLCJhdXRoIjoiWVdSdGFXNDZiRE00TldaeE1tSnJObms1WXpWaE1tUnViMjQ9In0sInJlZ2lzdHJ5LmRpZ2l0YWxvY2Vhbi5jb20iOnsidXNlcm5hbWUiOiJkb3BfdjFfMTRlNGRjNjBjYWU0NmRhZjI1MzNkOWE5YzRmNTgyMzg1NTBiZDc1Njg3MGUwMjRlZjBiOGM1ZTMxZWE5YjNmMCIsInBhc3N3b3JkIjoiZG9wX3YxXzE0ZTRkYzYwY2FlNDZkYWYyNTMzZDlhOWM0ZjU4MjM4NTUwYmQ3NTY4NzBlMDI0ZWYwYjhjNWUzMWVhOWIzZjAifSwiaGFyYm9yLnRoZXBvc3R3YXkuY29tIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InBvc3R3YXkwbkNsMHVjbCJ9fX0=
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardinal-stg
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: cardinal-stg
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIudGhlcG9zdHdheS5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoibDM4NWZxMmJrNnk5YzVhMmRub24iLCJhdXRoIjoiWVdSdGFXNDZiRE00TldaeE1tSnJObms1WXpWaE1tUnViMjQ9In0sInJlZ2lzdHJ5LmRpZ2l0YWxvY2Vhbi5jb20iOnsidXNlcm5hbWUiOiJkb3BfdjFfMTRlNGRjNjBjYWU0NmRhZjI1MzNkOWE5YzRmNTgyMzg1NTBiZDc1Njg3MGUwMjRlZjBiOGM1ZTMxZWE5YjNmMCIsInBhc3N3b3JkIjoiZG9wX3YxXzE0ZTRkYzYwY2FlNDZkYWYyNTMzZDlhOWM0ZjU4MjM4NTUwYmQ3NTY4NzBlMDI0ZWYwYjhjNWUzMWVhOWIzZjAifSwiaGFyYm9yLnRoZXBvc3R3YXkuY29tIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InBvc3R3YXkwbkNsMHVjbCJ9fX0=
---
apiVersion: v1
kind: Namespace
metadata:
  name: cardinal-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: cardinal-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodWIudGhlcG9zdHdheS5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoibDM4NWZxMmJrNnk5YzVhMmRub24iLCJhdXRoIjoiWVdSdGFXNDZiRE00TldaeE1tSnJObms1WXpWaE1tUnViMjQ9In0sInJlZ2lzdHJ5LmRpZ2l0YWxvY2Vhbi5jb20iOnsidXNlcm5hbWUiOiJkb3BfdjFfMTRlNGRjNjBjYWU0NmRhZjI1MzNkOWE5YzRmNTgyMzg1NTBiZDc1Njg3MGUwMjRlZjBiOGM1ZTMxZWE5YjNmMCIsInBhc3N3b3JkIjoiZG9wX3YxXzE0ZTRkYzYwY2FlNDZkYWYyNTMzZDlhOWM0ZjU4MjM4NTUwYmQ3NTY4NzBlMDI0ZWYwYjhjNWUzMWVhOWIzZjAifSwiaGFyYm9yLnRoZXBvc3R3YXkuY29tIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InBvc3R3YXkwbkNsMHVjbCJ9fX0=
