apiVersion: v1
kind: Namespace
metadata:
  name: operation
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: operation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0Y2MtaGFyYm9yLnBlYS5jby50aCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y2MyMDI0In19fQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: operation-stg
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: operation-stg
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0Y2MtaGFyYm9yLnBlYS5jby50aCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y2MyMDI0In19fQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: operation-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: operation-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0Y2MtaGFyYm9yLnBlYS5jby50aCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y2MyMDI0In19fQ==


# #ใช้ base64 ของ JSON ที่มี "https://tcc-harbor.pea.co.th"
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: operation
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: regcred
#   namespace: operation
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3RjYy1oYXJib3IucGVhLmNvLnRoIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InRjYzIwMjQifX19
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: operation-stg
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: regcred
#   namespace: operation-stg
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3RjYy1oYXJib3IucGVhLmNvLnRoIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InRjYzIwMjQifX19
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: operation-dev
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: regcred
#   namespace: operation-dev
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3RjYy1oYXJib3IucGVhLmNvLnRoIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6InRjYzIwMjQifX19
