apiVersion: v1
kind: Namespace
metadata:
  name: logistic
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: logistic
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0Y2MtaGFyYm9yLnBlYS5jby50aCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y2MyMDI0In19fQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: logistic-stg
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: logistic-stg
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0Y2MtaGFyYm9yLnBlYS5jby50aCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y2MyMDI0In19fQ==
---
apiVersion: v1
kind: Namespace
metadata:
  name: logistic-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: logistic-dev
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ0Y2MtaGFyYm9yLnBlYS5jby50aCI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJ0Y2MyMDI0In19fQ==
